apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    app: prometheus-node-exporter
  ports:
    - name: tcp
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30103
  type: NodePort
