apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30102
  type: NodePort
