apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  selector:
    app: pushgateway
  ports:
    - name: tcp
      protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
